### ISSUE TITLE
Multiple Gaussian Energies

### ISSUE THREAD

**Issue by nberkel05** [Q2MM/q2mm#12]
I ran a scan to produce several energies (in this example: 6). The HF line has them separated with a comma. It would be nice to be able to use the "-ge" functions on this log file. I know it's an easy fix, but I couldn't quite get it.
[scan.zip](https://github.com/Q2MM/q2mm/files/309790/scan.zip)

**Comment by arosale4** [comment]
I suppose the question is why you want to grab the energy from these log files? I'm sure you know each of those energies correspond to a new geometry. If you are trying to then run loop.py or compare.py you would somehow want to specify which geometry you want. The easiest thing I would suggest is just take those 6 structures and run 6 individual single point calculations, but ideally if you are using these for a compare.py, and loop.py you would want to inlcude the zero point energy, which I think only is given with a freq calculations? Again I suppose its important to know why you need the -ge to pick up the energies.

**Comment by nberkel05** [comment]
What I'm trying to do is to fit to these energies ultimately. So I'd use the loop.py and compare.py frequently. If you think it'd be easier to just do single point calculations, I could do that. I was just thinking it would be convenient to have it all within one file. 

I know I'll need to get the geometries as well. I can always just copy and paste those into maestro fairly quickly since I know it doesn't open scans properly. 

Again, if you don't think I should go about this in this way, then we can close this issue, and I'll do single point calculations instead.

**Comment by ericchansen** [comment]
This is a simple change, but you need the MM energies anyway, so you need
the .mae anyway. When you load the Gaussian .log in Maestro and save a .mae
from the structures, does the .mae have a property that's the Gaussian
energy? If so, that's another simple way of accessing them.

On my way to Chicago so I won't have a computer to code this until Monday.

**Comment by arosale4** [comment]
I haven't found a way to convert Gaussian log files into maestro mae files with the energies. I think it would be easier just to take those 6 structures you have and save them into separate gaussian com files. I may be wrong but since they are the same structure you should be able to get away with a single point calc rather than having to obtain the zero-point energies. Not sure if the code recognizes the energies if you don't have zp in the archive.

**Comment by ericchansen** [comment]
My plan is to add a line in constants called ```GAU_EN``` where you can
change the string to be ```['HF']```, ```['ZeroPoint']```, ```['HF',
'ZeroPoint']```, etc. Then you can choose what type of energy to use
without changing code.

Also will make it so ```-ge``` can tell whether it's one or multiple
energies. Very simple to add a check with ```if ',' in whatever:``` or
```try: float(whatever)```.

Again, I just need a computer to do this, so probably Monday. Someday I
will have a laptop.

**Comment by ericchansen** [comment]
Okay, all the changes needed should be there. Neil, could you pull branch iss12 and see if this addresses your needs? Be sure to check out the commit messages for how to use the new features.

If it all works, then we can close this issue.

**Comment by nberkel05** [comment]
Just checked this out. Works for me. It's good to be merged.
