### ISSUE TITLE
Not using best force field in final test

### ISSUE THREAD

**Issue by peonor** [Q2MM/q2mm#32]
I'm using the following input to loop.py (no Simplex):

FFLD read mm3.fld
PARM fpar
RDAT -geigz S1.log S2.log S3.log S4.log S5.log S6.log S7.log S8.log S9.log S10.log S11.log S12.log S13.log S14.log -jt AllNtP.mae
CDAT -mgeig S1.mae,S1.log S2.mae,S2.log S3.mae,S3.log S4.mae,S4.log S5.mae,S5.log S6.mae,S6.log S7.mae,S7.log S8.mae,S8.log S9.mae,S9.log S10.mae,S10.log S11.mae,S11.log S12.mae,S12.log S13.mae,S13.log S14.mae,S14.log -mt AllNtP.mae
COMP -o fstart.txt
LOOP 0.01
GRAD
END
CDAT
COMP -o fend.txt

The loop end without improvements (strange, because there are a number of large 1st derivatives, and one of the differentiation steps had a score of 140805, should have been picked as improvement):

---------------- Cycle 1 Summary -----------------
| PF Score:               152157.454149118391797 |
| % change:                    0.000000000000000 |
--------------------------------------------------
  -- Wrote best FF to ./mm3_008.fld
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ CALCULATING FF DATA ~~

WhenI look in "fend.dat", this is not the result from the final force field! Here are the lines near the end of fend.dat:


-----------------------------------------------------------------------------------------
Total score:                  176793.4600
Num. data points:                   87936
-----------------------------------------------------------------------------------------

This is not the score from the best force field, but from the last to be tested (and SVD solution). Obviously, the final COMP must use the best force field so far.

**Comment by ericchansen** [comment]
Well, in your input it says the results from the final FF should be in `fend.txt`, not `fend.dat`. Not sure if that's the problem.

Also, the final COMP is not the best FF unless you tell it to write the best FF. This is relatively clear in `README.md`.

As the log says, the best FF is in `mm3_008.fld`.
