### ISSUE TITLE
Problem in Simplex

### ISSUE THREAD

**Issue by peonor** [Q2MM/q2mm#33]
I've turned off massive contraction, setting the boolean to False. The major motivation is that if one parameter has a too large influence, it needs to be contracted several times to get into balance with the others, but a massive contraction will decrease all parameters, maintaining the bad balance. However, without the massive contraction, I notice an error. After a contraction, the new value should ALWAYS replace the previous worst, regardless of whether the contraction failed or not. Otherwise, the same step will simply be repeated over and over.

**Comment by peonor** [comment]
Also, found another problem in the weighted reflection, they've been going the wrong way. The problem is in line 261-263, the points are weighted by score_diff_sum, they should instead be weighted between the difference between the worst score and the current score, and there needs to be a for loop over x!

**Comment by ericchansen** [comment]
In your 1998 paper, you say, "If pK [contraction] is better than pN [2nd worst parameter set], replace pW [worst] by pK, continue with next cycle". That's what's in the code right now, but we can change it if you'd like.

**Comment by peonor** [comment]
Yes, but that is in the case where we do massive contraction. It should still work when we turn it off, and the really important thing is that there is a difference from the previous cycle, otherwise it will just repeat that cycle over and over. The easiest way is to simply accept the contracted as the new worst point, and do a reflection from that.
There is a risk that the contractions continue until no change is obtained on contraction. At that point, either break the simplex and go back in the loop, or (something no-one has done before) drop the point and continue with one dimension less in the simplex.
I've looked at a few cases now where most points in the simplex are good, but 2 or 3 stick out as really bad. It could be possible to do a partial massive contraction in that case, for example, only contract the points that are closer to the "worst" (or "2nd worst") than to the "best". Might play with a few things like that myself, when I have some free time. Or throw such ideas at some random programmer with lots of free time :-)

**Comment by peonor** [comment]
But for the current problem, I think the safe solution is to FIRST replace the worst point with the contracted point, and THEN figure out, from the test you stated and the boolean, if you want to do massive contraction.

**Comment by peonor** [comment]
In my case, the problem got worse because the inversion point was calculated incorrectly, I think that's more important. I hope you don't mind mixing these two related problems in the same issue.

**Comment by ericchansen** [comment]
Yea looking into the inversion now. The bug was introduced here in commit e40261269dbc07416.

I forgot the for loop. I think that means that the `x` used on the lines that calculate [`inv_val`](https://github.com/Q2MM/q2mm/blob/aeeacc5a34a7807a27092df7669bc1cd538630eb/simplex.py#L261-L263) was the the last FF  `x` in `self.new_ffs` from previously calculating [`score_diff_sum`](https://github.com/Q2MM/q2mm/blob/aeeacc5a34a7807a27092df7669bc1cd538630eb/simplex.py#L247-L248). Or if `self.do_weighted_reflection = False`, then it would be the last FF in `self.new_ffs` from line [211](https://github.com/Q2MM/q2mm/blob/aeeacc5a34a7807a27092df7669bc1cd538630eb/simplex.py#L211). Scary how reusing a variable like `x` can lead to obvious bugs like this to slipping by.

Also, I'm thinking that I misinterpreted what you meant originally in ericchansen/q2mm#22, which resulted in commit e40261269dbc0741. We are only dividing by `score_diff_sum`, and that is the only part that doesn't change, which you recommended calculating outside the loop. The numerator does change.

Can you double check the [calculation of the inversion point](https://github.com/Q2MM/q2mm/blob/dec6d7ed20fcc6bba27d52cd8ab8eb130c480210/simplex.py#L261-L265) now in commit dec6d7e?

**Comment by ericchansen** [comment]
And one more point of clarification about the contraction scheme.

If we use massive contraction, you want to massive contract the original vertices with the last one replaced by the contraction, call it `[x1, x2, x3, x4, c5]`? So we would massive contract those 5 parameter sets, not the original vertices `[x1, x2, x3, x4, x5]`, right?

**Comment by peonor** [comment]
I believe this is correct.

**Comment by peonor** [comment]
I don’t know, I believe your scheme for massive contraction is what was proposed for original simplex. What would make most sense is to take the lowest of the three (worst, reflected, contracted), and use that in the massive contraction. Either way you want to do it is fine. Massive contraction means that some has gone badly wrong anyway…

Should we continue discussing this? I don’t know the best answers, but I have some understanding to share. The main use of massive contraction is when different points of the simplex has ended up in two different minima, and the intention is to drag all points into only one minimum and continue there. The drawback is that this drastically reduces the search hypervolume (by a factor 1024 for 10 parameters), whereas contraction and expansion only change by exactly a factor of 2, so you need many expansions after a massive contraction to get back to efficient searching over a significant hypervolume. Thus, I don’t want to do it frequently, I want to give the method a chance to contract only the bad search direction first (happens whenever a parameter has a too large differentiation step). But it should be there to solve cases where simplex has bogged down (the reason I took it away is that I don’t believe in multiple close-lying minima on a quadratic score function).

We have the option of differentiating between more cases. The contraction only succeeds if pK is better than pN. However, it could fail completely by being worse than pW (in which case do a massive contraction). It could fail partially by being better than pW but worse than pN. I’d like to allow a number of partial failures before falling back on massive contraction. I don’t know how many. 3? The number of parameters? Remember, these are there to take care of the case when ONE parameter have a much too large step, and you want to let the contractions reduce the step size for that parameter only before you do massive contractions, which wouldn’t solve the imbalance since all steps would be reduced.

And just to give you another idea to think of. Let’s say we’ve had a partial failure, pK is better than pW but worse than pN. I’ve thought of an alternative fix; reduce the dimensionality for one step, replace pW with pK and then take it away from consideration for one step. That would cause pN to be the new worst, reflecting that through the remaining points, and then bring back pK again. It will now certainly be the worst point, but you have restored the dimensionality, and it will explore a new, hopefully better, hypervolume since the inversion point has changed. Successive contractions of the same point will obviously always use the same inversion point.

/Per-Ola

**Comment by arosale4** [comment]
First, I need to check if this problem is consistent.
Simplex seems to only use the first 10 parameters in the parameters text file. Even when there are several parameters that have much lower 2nd derivatives. Keep this in mind when using simplex.

**Comment by ericchansen** [comment]
Look at the changes in the branch ericchansen@8f40a691e62ab4. Should address your issue.

**Comment by ericchansen** [comment]
Revisiting what has to be done for this issue. I'm assuming that Tony's last concern has already been addressed, but let me know if I'm incorrect.

1. Setup some method for catching partial failures, perhaps defined by 3 failed parameter steps.
2. Have an option to attempt massive contraction only after partial failure. Massive contraction should probably not be used as it currently is by default.
3. Have this option described by PO below instead of massive contraction.

> Let’s say we’ve had a partial failure, pK is better than pW but worse than pN. I’ve thought of an alternative fix; reduce the dimensionality for one step, replace pW with pK and then take it away from consideration for one step. That would cause pN to be the new worst, reflecting that through the remaining points, and then bring back pK again. It will now certainly be the worst point, but you have restored the dimensionality, and it will explore a new, hopefully better, hypervolume since the inversion point has changed.
