### ISSUE TITLE
Merging structures with different bonds

### ISSUE THREAD

**Issue by jesswahlers** [Q2MM/q2mm#40]
An issue has arose with trying to merge a new ligand onto the template I have for the palladium allyl TSFF. The pattern that I am currently using is N0.Pd.P3, but the problem arises that the nitrogen and phosphorus are bonded in the new ligand. The template does not have these atoms bonded together. The new ligand is a phosphoramidite ligand while the typical ligand used is a PHOX ligand.  This leads to me getting the error 'NoneType' object has no attribute 'property'. Is there a way to have different bonding parameters in the pattern between the ligand and the template. 

In merge_structures_from_matchign_atoms() function the coding logic tries to determine if a bond is present in structure1 just like the bond in structure2. If it does then it simply tries to copy parameters, if it doesn't then it adds in a new bond. This is determined by comparing if the atom2 in the bond object is in the list of common atoms. In this case, the N0 and P3 atoms are in the list of common atoms but there is still no bond between them in the template so no new bond is created. 

Using merge.py -g template_2.mae -g phosphoramidite.mae 

[atom.typ.txt.txt](https://github.com/Q2MM/q2mm/files/1334889/atom.typ.txt.txt)
[mm3.fld.txt](https://github.com/Q2MM/q2mm/files/1334891/mm3.fld.txt)
[template_2.mae.txt](https://github.com/Q2MM/q2mm/files/1334901/template_2.mae.txt)
[phosphoramidite.mae.txt](https://github.com/Q2MM/q2mm/files/1334904/phosphoramidite.mae.txt)

**Comment by ericchansen** [comment]
Fix with pull #41. Cheers!

**Comment by peonor** [comment]
Hi Jess,

I saw that you got an answer from Eric, but in addition to that, I think you’re trying to use the force field improperly. In a phosphoramidate, ONLY the P will coordinate to Pd, the N cannot bind at the same time. The pattern should only match if you’ve drawn a bond to the nitrogen also. Please don’t.

BTW, I still need to go through all the material you sent, it’s been a bit hectic here the last couple of weeks…

/Per-Ola

**Comment by jesswahlers** [comment]
Yeah I figured those ligands wouldn't work since the transition state was different. I just won't use them. Thanks

**Comment by ericchansen** [comment]
Can someone sign off that this was fixed with PR #41 and close this issue?
