### ISSUE TITLE
Params objects cannot be set exactly to their minimum allowed values

### ISSUE THREAD

**Issue by jeherr** [Q2MM/q2mm#51]
Parameters set to exactly the minimum allowed value in their range cause an infinite loop of resetting the step size for the Param object when generating the FFs for taking gradients. I suspect the same happens at the maximum allowed value of the range as well. 

The issue occurs in [this try and except block](https://github.com/Q2MM/q2mm/blob/c65b6da14f26f5a3be176a93ff11178975692b9e/q2mm/opt.py#L183-L205). The exception occurs to shrink the step size so that the value for forward or backward differentiation stays within the allowed range for the param. When the step size is reset, [this block prevents the step size from being 0.0 and resets it to 0.1](https://github.com/Q2MM/q2mm/blob/c65b6da14f26f5a3be176a93ff11178975692b9e/q2mm/datatypes.py#L100-L101). So if a param is at exactly the minimum or maximum allowed value, this causes an infinite loop of trying to reset the step size. 

Also, this occurs when setting up the FFs for calculating the numeric gradients w.r.t. the params, and I don't see why the params shouldn't be allowed to go outside of the allowed range when calculating the gradients, so long as they stay positive if negative values aren't allowed and the params stay within the range when updates are applied after all the gradients have been collected. The hard limit on the actual params should prevent the gradient params from going very far outside of the allowed range.

Possible solutions I can think of are

1. Catch whether the param is at the minimum or maximum allowed value and only take the gradient by differentiating in the opposite direction. This should be pretty easy to implement and would reduce the number of calculations needed for collecting the comparison data by a small bit. Also avoids going outside the range of allowed values so there would be no problem with any totally nonsensical params. May require all derivatives to be calculated in only one direction for that particular loop iteration though. 

2. Slightly perturb the param in the direction opposite the barrier. Easiest to implement, but probably leads to some wasteful calculations being done. Would keep things pretty much as the are now.

3. Inherit a new Param class specifically for FFs used to calculate gradients which doesn't have a hard limit on the allowed range, or slightly tweak the allowed range to catch when it may be OK to go outside the range and when it should not. This one is the most work to implement and probably not worth the payoff. Also could lead to a lot more issues trying to do this correctly.

**Comment by ericchansen** [comment]
Some thoughts.

1. Could this possibly lead to infinite loops on its own? Ex. Forward gradient moves param off minimum value, central gradient puts it back? I _think_ this is possible, but I certainly haven't checked the math.
2. and 3. I don't know. Does this really solve the fundamental problem?

Let's think about some use cases where we restrict parameters. Why are we setting limits? What are the limits we're using?

Sometimes, I would set limits because I knew from empirical evidence that the value for a parameter should be roughly _something_. Thanks to chemical intuition or knowledge of empirical force constants, bond distances, etc. I wanted to _encourage_ parameters to end up in a local minima that make sense to us as chemists. Let's call these soft limits.

On the other hand, some things, like equilibrium distances, should never be negative. Why should the optimizer ever drive a bond distance negative? It's likely that the reference data isn't suited to the parameter set being optimized. This might not be a problem with the optimizer, but actually a problem with the user's decisions. 😊 Let's call these hard limits.

Some ideas on how we could do this.

- For hard limits, we raise an exception and abort the optimization. The user likely needs to think about what they're attempting to do. Having a hard wall, as we do now, might encourage misuse.
- Soft limits are more fun. We want to use our intuition to _push_ a parameter to a certain range or ideal value. In that sense, why don't put the parameter in a harmonic potential (or something similar) centered on the idealized value? This is similar to the existing parameter tethering.
- So how do we do a medium limit? A relatively flat bottom potential, but the potential walls could exponentially approach infinity. I suppose this would probably factor into the objective function. If we did this, I don't think we'd have to deal with parameters ever hitting the limit assuming we actually apply an infinite potential at the barriers. This might have weird side effects.

**Comment by jeherr** [comment]
I think maybe there is a bit of a miscommunication in what I mean here. The infinite loop I described here occurs because of the while loop when defining the set of FFs for taking the gradients. In the while loop if the forward or backward step for the param goes outside the allowed range, the step size gets reset to the minimum of the difference between the param and the max limit or the min limit. If the param is equal to the min limit, then the step size is set to 0.0. When the step size gets reset in the param object, this disallows the param step size to be set to 0.0 and so it resets it to 0.1. Then on the next iteration of the while loop, this step size is again too big so it again trys to reset it to 0.0. This just leads to Q2MM continually throwing ParamError exceptions and the while loop is never exited for that param. Purely from a programming perspective that shouldn't happen. Q2MM has to either correct it automatically, or a system-exiting error needs to be thrown telling the user to move the param off of the barrier. While I think we should consider the points you raised here in the solution, I want to point out that this doesn't necessarily occur because the gradient points toward the limit, but just because the backward differentiation isn't able to be set because it also cannot go beyond the hard limit.

I think you raise some good points to consider here about the cause of the gradients pointing beyond the limits as they are currently set, though I think it may be different than what I opened this issue about. They're certainly closely related but I think distinct enough that maybe the discussion of hard vs soft limits and exiting when the user has given Q2MM an ill-defined problem should go to their own separate issue thread. I think the points you raise would be more of an improvement issue, but this one is purely a bug.

**Comment by peonor** [comment]
In my original code, long before python, this was not a loop, but just applied serially, the allowed max and min overrides everything else. This could give step size problems, but in my experience not serious.

As an aside, this was part of why I wanted to investigate optimizing parameters in log space instead (for parameters that should never go below zero). Never tried…

/Per-Ola

**Comment by ericchansen** [comment]
+1 to what @peonor said, but after reading your last comment @jeherr, I see what you mean now. Let's keep this issue to the bug that you reported. We can open up enhancement issues for the others if anyone has time to work on them.

**Comment by ericchansen** [comment]
It sounds like I wrote a poorly designed while loop. :sweat_smile:

I personally think we should raise a system exiting exception when a parameter value is equal to a limit. I'm open to any solutions really, but maybe let's avoid adding in complicated self-correction procedures. When this happens, the user should really intervene and rethink what they're doing.

**Comment by jeherr** [comment]
I think I disagree that a parameter being equal to a limit should necessarily be a system exiting exception. This is only a problem if the gradients are pointing beyond the limit, and it's possible that the gradient is only pointing beyond the limit locally based on all the other parameters current values.

For example, if you start a torsion parameter at 0.1 (lower limit) then the gradients may still point to a higher value for that parameter which would be fine. It seems like causing a system exiting error here and telling the user to rethink what they're doing would lead to unnecessary confusion. 

On the other hand if the torsion parameter was at 0.1 and the gradient pointed towards lower values I could see throwing a system exiting exception in this case. I mentioned above that the gradient could just be pointing beyond the limit locally but the global minimum could still be within the limits. That's just my understanding of optimization problems in general though. I don't know if that happens commonly in Q2MM and I'm guessing the starting with a good initial guess of all parameters likely wouldn't have that problem, which falls back then to the user needs to rethink what they're doing.

My suggestion would be, if the parameter is at a limit then Q2MM needs to handle that somehow, but if the gradient of that parameter at the limit points outside of the limit then Q2MM should throw a system exiting exception.

**Comment by peonor** [comment]
John, I agree. The parameterization should finalize, the problem may take care of itself, and if not, it would be great to have a flag notifying the user of a potential problem, but I wouldn’t want to have the program quitting at this point.

/Per-Ola

**Comment by ericchansen** [comment]
So it sounds like

- Parameter at limit - Okay
- Parameter at limit with gradient pointing outside limits - Raise exception
- Parameter at limit with gradient pointing inside limits - Okay

**Comment by peonor** [comment]
Again, I would only want the exception if the condition persists, so please only check this at the end, not in every cycle. If gradient points outside, the step should be set to zero for this parameter, but that’s already in there, right?

I do want a warning flag at the end of the parameter optimization.

Cheers,

Per-Ola

**Comment by jeherr** [comment]
I'm good with what Per-Ola has suggested. Looping once over every parameter at the end just to check if it is at a limit and raising a warning should be easy to implement and I can probably do that this week.

My only question is how I should deal with parameters which are at a limit during an optimization, because the gradient can't go outside of the limit either, which is what causes the infinite loop that I started this issue over.

Simplest solution would be to automatically perturb the parameter itself slightly away from its limit.

Maybe a bit more work to do would be to only take the gradient by forward or backward differentiation for that parameter. Might be more difficult and has more room for adding new bugs while implementing this.

Last way I can think of is to handle gradients as their own new class of params which could be a lot more flexible in the way some gradients could be taken but ultimately would take a lot more work.

Opinions or other suggestions? For now at least I think just slightly perturbing the param off the limit would be fine.

**Comment by peonor** [comment]
Hi John,

Please check me on this, but at least in my old implementation, the way we calculated first and second derivatives from the three points would actually allow two of the points to be the same without crashing. Say that the parameter value at the center is p, and the slightly displaced parameter values are pp and pm. The function values at those points are f, fp, and fm. The formulas for the first and second derivatives are then

f’ = (fp-fm)/(pp-pm)
f” = 4(fp+fm-2f)/(pp-pm)^2

None of those formulas will crash if p=pm & f=fm. The first derivative simply becomes the forward differentiation, no need  to make a special case, and the second derivative is only used in a 1D-step which we don’t use anymore (I think), and the value works there anyway (the step will become (pp-pm)/4).

My point is you can allow the backwards step to be zero, and the same point being calculated again, it won’t have any bad effects.

Cheers,

Per-Ola

**Comment by jeherr** [comment]
Very good point Per-Ola. Those do indeed just simplify to lower-order numerical approximations. This seems like the best solution to me.
