### ISSUE TITLE
Gradient defaults

### ISSUE THREAD

**Issue by ericchansen** [Q2MM/q2mm#9]
I think we should decide what our default options are for gradient. These are given in [```gradient.Gradient.__init__```](https://github.com/Q2MM/q2mm/blob/d64646574b9bed9f5d45dc01628ec1d353b9f4e4/gradient.py#L72-L105). Personally, I'm not sure what everyone thinks is best, so I'd be interested in some discussion.

**Comment by ericchansen** [comment]
Okay so, maybe this will help spark discussion.

I like Per-Ola's idea of smart SVD thresholds that he brought up in this ericchansen/q2mm/issues/28, but we have to stick with simple floats for now.

Here's what is currently in master.

```
self.lstsq_cutoffs = None
self.lstsq_radii = None
self.lagrange_factors = [0.01, 0.1, 1., 10.]
self.lagrange_cutoffs = None
self.lagrange_radii = [0.1, 1., 5., 10.]
self.levenberg_factors = [0.01, 0.1, 1., 10.]
self.levenberg_cutoffs = None
self.levenberg_radii = [0.1, 1., 5., 10.]
self.newton_cutoffs = None
self.newton_radii = None
self.svd_factors = [0.001, 0.01, 0.1, 1.]
self.svd_cutoffs = [0.1, 10.]
self.svd_radii = None
```

I imagine that the radii work better than cutoffs in most cases, so perhaps that should always be the default (despite being more time consuming from generating more trial FFs)? In which case, perhaps radii like `[1., 5., 10.]` would suffice.

The least squares method definitely should have at least some form of radius limiting check (probably radii as per above).

I feel that SVD generates great solutions, after removing the absurdly large diagonal elements of the inverted s matrix (see the discussion on this [issue](https://github.com/ericchansen/q2mm/issues/28) for explanation of matrices). What is absurdly large? Perhaps things above 100? Or perhaps above 10? Also, probably generates too many trial FFs without using thresholds. I propose `[0.5, 1., 10., 100.]` for thresholds.

This leaves the Lagrange and LM factors. Honestly, I have very few ideas about what's best for these right now.

**Comment by ericchansen** [comment]
Actually, SVD may be more suited for cutoffs.

**Comment by peonor** [comment]
OK, I think the default could be to skip LSTSQ and Levenberg. The Lagrange usually does all these two do, and is more stable. Which factors to use is dependent on the situation; really low values speed up convergence, but also risks taking a very wrong step, whereas a high factor will always give a short step in a correct direction, but gives slow convergence. I think the current four ones are good. But we could have fewer radii. The very small values will rarely give the optimum convergence. Should we say [1.,10.]?

For the SVD, again I believe the current factors are a good compromize. The cutoffs seem good.

**Comment by peonor** [comment]
And yes, due to the nature of SVD, if we have a solution with too high radius, there is probably no reason to scale it down using radii, so let's just use the cutoffs here. And with just four factors, maybe we don't even need those, but can just accept all four solutions. If we, in the future, implement some smart selection that gives us many more SVD solutions, it would make more sense to apply these cutoffs. Not radii though.

**Comment by ericchansen** [comment]
I like the idea of less radii, so `[1., 10.]`.

Then again, with a large parameter set, you probably want more trial FFs to optimize the time spent during central differentiation vs. evaluating trials. Oh well, that can be left to the user. The defaults should probably err on the simple side.

**Comment by peonor** [comment]
I commented on the commit. Time to close this issue?

**Comment by ericchansen** [comment]
No has pulled the changes yet into master. I'm happy with them though, so I will close this once someone merges into master.
